export const Genres = Object.freeze(
    [
        "Akční",
        "Animovaný",
        "Dobrodružný",
        "Dokumentární",
        "Drama",
        "Fantasy",
        "Historický",
        "Horror",
        "Komedie",
        "Krimi",
        "Mysteriózní",
        "Romantický",
        "Sci-Fi",
        "Triller",
        "Válečný",
        "Western",
        "Životopisný",
    ]
);